import { CardConfig } from "./types";

export const CARD_GROUPS = [
  { id: 1, name: "基本信息", icon: "👶" },
  { id: 2, name: "期望与寓意", icon: "✨" },
  { id: 3, name: "家族信息", icon: "👨‍👩‍👧" },
  { id: 4, name: "文化偏好", icon: "🎋" },
  { id: 5, name: "生活背景", icon: "🏠" },
  { id: 6, name: "自由补充", icon: "🎤" },
];

export const CARDS: CardConfig[] = [
  // 第 1 组：基本信息
  {
    id: "surname",
    group: 1,
    groupName: "基本信息",
    type: "text-input",
    title: "宝宝姓什么？",
    description: "支持复姓，如「欧阳」「司马」",
    field: "surname",
    placeholder: "请输入姓氏",
    required: true,
  },
  {
    id: "gender",
    group: 1,
    groupName: "基本信息",
    type: "select",
    title: "是男孩还是女孩？",
    field: "gender",
    options: [
      { label: "男孩", value: "boy" },
      { label: "女孩", value: "girl" },
      { label: "不限", value: "neutral" },
    ],
    required: true,
  },
  {
    id: "birthDate",
    group: 1,
    groupName: "基本信息",
    type: "date-picker",
    title: "宝宝的出生日期",
    description: "用于八字五行分析（可跳过）",
    field: "birthDate",
  },

  // 第 2 组：期望与寓意
  {
    id: "traits",
    group: 2,
    groupName: "期望与寓意",
    type: "multi-select",
    title: "希望宝宝拥有怎样的性格？",
    description: "可多选，最多选 3 个",
    field: "traits",
    options: [
      { label: "勇敢", value: "勇敢" },
      { label: "温柔", value: "温柔" },
      { label: "聪慧", value: "聪慧" },
      { label: "坚韧", value: "坚韧" },
      { label: "乐观", value: "乐观" },
      { label: "沉稳", value: "沉稳" },
      { label: "活泼", value: "活泼" },
      { label: "独立", value: "独立" },
    ],
  },
  {
    id: "wishes",
    group: 2,
    groupName: "期望与寓意",
    type: "multi-select",
    title: "对宝宝的人生有什么愿景？",
    description: "可多选，最多选 3 个",
    field: "wishes",
    options: [
      { label: "学业有成", value: "学业有成" },
      { label: "事业顺遂", value: "事业顺遂" },
      { label: "健康平安", value: "健康平安" },
      { label: "才华横溢", value: "才华横溢" },
      { label: "品德高尚", value: "品德高尚" },
      { label: "幸福美满", value: "幸福美满" },
    ],
  },
  {
    id: "style",
    group: 2,
    groupName: "期望与寓意",
    type: "slider",
    title: "名字的风格偏好",
    field: "style",
    min: 1,
    max: 10,
    minLabel: "古典诗词风",
    maxLabel: "现代简约风",
  },

  // 第 3 组：家族信息
  {
    id: "fatherName",
    group: 3,
    groupName: "家族信息",
    type: "text-input",
    title: "父亲的名字",
    description: "AI 会参考用字，避免重复或呼应传承",
    field: "fatherName",
    placeholder: "请输入全名",
  },
  {
    id: "motherName",
    group: 3,
    groupName: "家族信息",
    type: "text-input",
    title: "母亲的名字",
    field: "motherName",
    placeholder: "请输入全名",
  },
  {
    id: "generationChar",
    group: 3,
    groupName: "家族信息",
    type: "text-input",
    title: "有辈分字要求吗？",
    description: "如家族有辈分字传统，请输入指定字",
    field: "generationChar",
    placeholder: "无则跳过",
  },
  {
    id: "avoidChars",
    group: 3,
    groupName: "家族信息",
    type: "text-input",
    title: "需要避讳的字",
    description: "长辈名字中的字或其他需要回避的字",
    field: "avoidChars",
    placeholder: "多个字用空格分开",
  },

  // 第 4 组：文化偏好
  {
    id: "wuxing",
    group: 4,
    groupName: "文化偏好",
    type: "multi-select",
    title: "五行偏好",
    description: "希望名字中包含哪些五行属性？",
    field: "wuxing",
    options: [
      { label: "金", value: "金" },
      { label: "木", value: "木" },
      { label: "水", value: "水" },
      { label: "火", value: "火" },
      { label: "土", value: "土" },
      { label: "不限", value: "不限" },
    ],
  },
  {
    id: "nameLength",
    group: 4,
    groupName: "文化偏好",
    type: "select",
    title: "名字字数偏好",
    field: "nameLength",
    options: [
      { label: "两字名", value: "two" },
      { label: "三字名", value: "three" },
      { label: "都可以", value: "any" },
    ],
  },
  {
    id: "pronunciation",
    group: 4,
    groupName: "文化偏好",
    type: "slider",
    title: "发音偏好",
    field: "pronunciation",
    min: 1,
    max: 10,
    minLabel: "响亮开口音",
    maxLabel: "柔和闭口音",
  },

  // 第 5 组：生活背景
  {
    id: "hobbies",
    group: 5,
    groupName: "生活背景",
    type: "multi-select",
    title: "家庭的爱好兴趣",
    description: "帮助 AI 融入生活元素",
    field: "hobbies",
    options: [
      { label: "文学", value: "文学" },
      { label: "音乐", value: "音乐" },
      { label: "运动", value: "运动" },
      { label: "旅行", value: "旅行" },
      { label: "科技", value: "科技" },
      { label: "艺术", value: "艺术" },
      { label: "自然", value: "自然" },
      { label: "美食", value: "美食" },
    ],
  },
  {
    id: "location",
    group: 5,
    groupName: "生活背景",
    type: "text-input",
    title: "居住城市",
    description: "可能会融入地域文化特色",
    field: "location",
    placeholder: "如：杭州、成都",
  },
  {
    id: "existingNames",
    group: 5,
    groupName: "生活背景",
    type: "text-input",
    title: "已有兄弟姐妹或宠物的名字",
    description: "用于风格统一或避免重复",
    field: "existingNames",
    placeholder: "多个名字用空格分开",
  },

  // 第 6 组：自由补充
  {
    id: "freeText",
    group: 6,
    groupName: "自由补充",
    type: "voice-input",
    title: "还有什么想告诉 AI 的？",
    description: "比如一个故事、一段回忆、一个特别的期望...",
    field: "freeText",
    placeholder: "点击麦克风语音输入，或直接打字",
  },
];
